# Generated by Django 3.1.6 on 2021-02-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_off_led_if_light', models.IntegerField(default=1)),
                ('light_start_hour', models.IntegerField(default=6)),
                ('light_end_hour', models.IntegerField(default=19)),
                ('ambient_temp', models.IntegerField(default=30)),
                ('ambient_humidity', models.IntegerField(default=50)),
                ('soil_humidity', models.IntegerField(default=50)),
            ],
        ),
    ]
